// Code generated by ent, DO NOT EDIT.

package grocery

const (
	// Label holds the string label denoting the grocery type in the database.
	Label = "grocery"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// EdgeProvider holds the string denoting the provider edge name in mutations.
	EdgeProvider = "provider"
	// Table holds the table name of the grocery in the database.
	Table = "groceries"
	// ProviderTable is the table that holds the provider relation/edge.
	ProviderTable = "groceries"
	// ProviderInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	ProviderInverseTable = "users"
	// ProviderColumn is the table column denoting the provider relation/edge.
	ProviderColumn = "user_provided_groceries"
)

// Columns holds all SQL columns for grocery fields.
var Columns = []string{
	FieldID,
	FieldName,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "groceries"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"user_provided_groceries",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}
