// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// GroceriesColumns holds the columns for the "groceries" table.
	GroceriesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString},
		{Name: "price", Type: field.TypeInt},
		{Name: "unit", Type: field.TypeInt},
		{Name: "expiration_date", Type: field.TypeTime},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "user_provided_groceries", Type: field.TypeInt, Nullable: true},
	}
	// GroceriesTable holds the schema information for the "groceries" table.
	GroceriesTable = &schema.Table{
		Name:       "groceries",
		Columns:    GroceriesColumns,
		PrimaryKey: []*schema.Column{GroceriesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "groceries_users_provided_groceries",
				Columns:    []*schema.Column{GroceriesColumns[6]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// LedgersColumns holds the columns for the "ledgers" table.
	LedgersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "price", Type: field.TypeInt},
		{Name: "type", Type: field.TypeEnum, Enums: []string{"purchase", "cash", "etc"}},
		{Name: "user_payer", Type: field.TypeInt, Nullable: true},
		{Name: "user_receiver", Type: field.TypeInt, Nullable: true},
	}
	// LedgersTable holds the schema information for the "ledgers" table.
	LedgersTable = &schema.Table{
		Name:       "ledgers",
		Columns:    LedgersColumns,
		PrimaryKey: []*schema.Column{LedgersColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "ledgers_users_payer",
				Columns:    []*schema.Column{LedgersColumns[3]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.SetNull,
			},
			{
				Symbol:     "ledgers_users_receiver",
				Columns:    []*schema.Column{LedgersColumns[4]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// PurchasesColumns holds the columns for the "purchases" table.
	PurchasesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "price", Type: field.TypeInt},
		{Name: "amount", Type: field.TypeInt},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "grocery_purchased", Type: field.TypeInt},
		{Name: "user_purchased", Type: field.TypeInt},
	}
	// PurchasesTable holds the schema information for the "purchases" table.
	PurchasesTable = &schema.Table{
		Name:       "purchases",
		Columns:    PurchasesColumns,
		PrimaryKey: []*schema.Column{PurchasesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "purchases_groceries_purchased",
				Columns:    []*schema.Column{PurchasesColumns[4]},
				RefColumns: []*schema.Column{GroceriesColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "purchases_users_purchased",
				Columns:    []*schema.Column{PurchasesColumns[5]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString},
		{Name: "password", Type: field.TypeString},
		{Name: "balance", Type: field.TypeInt, Default: 0},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		GroceriesTable,
		LedgersTable,
		PurchasesTable,
		UsersTable,
	}
)

func init() {
	GroceriesTable.ForeignKeys[0].RefTable = UsersTable
	LedgersTable.ForeignKeys[0].RefTable = UsersTable
	LedgersTable.ForeignKeys[1].RefTable = UsersTable
	PurchasesTable.ForeignKeys[0].RefTable = GroceriesTable
	PurchasesTable.ForeignKeys[1].RefTable = UsersTable
}
