// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent/dialect/sql"
	"github.com/nishinoyama/kobuy-2/ent/balancelog"
	"github.com/nishinoyama/kobuy-2/ent/user"
)

// BalanceLog is the model entity for the BalanceLog schema.
type BalanceLog struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Price holds the value of the "price" field.
	Price int `json:"price,omitempty"`
	// Type holds the value of the "type" field.
	Type balancelog.Type `json:"type,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the BalanceLogQuery when eager-loading is set.
	Edges         BalanceLogEdges `json:"edges"`
	user_donor    *int
	user_receiver *int
}

// BalanceLogEdges holds the relations/edges for other nodes in the graph.
type BalanceLogEdges struct {
	// Donor holds the value of the donor edge.
	Donor *User `json:"donor,omitempty"`
	// Receiver holds the value of the receiver edge.
	Receiver *User `json:"receiver,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// DonorOrErr returns the Donor value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e BalanceLogEdges) DonorOrErr() (*User, error) {
	if e.loadedTypes[0] {
		if e.Donor == nil {
			// Edge was loaded but was not found.
			return nil, &NotFoundError{label: user.Label}
		}
		return e.Donor, nil
	}
	return nil, &NotLoadedError{edge: "donor"}
}

// ReceiverOrErr returns the Receiver value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e BalanceLogEdges) ReceiverOrErr() (*User, error) {
	if e.loadedTypes[1] {
		if e.Receiver == nil {
			// Edge was loaded but was not found.
			return nil, &NotFoundError{label: user.Label}
		}
		return e.Receiver, nil
	}
	return nil, &NotLoadedError{edge: "receiver"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*BalanceLog) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case balancelog.FieldID, balancelog.FieldPrice:
			values[i] = new(sql.NullInt64)
		case balancelog.FieldType:
			values[i] = new(sql.NullString)
		case balancelog.ForeignKeys[0]: // user_donor
			values[i] = new(sql.NullInt64)
		case balancelog.ForeignKeys[1]: // user_receiver
			values[i] = new(sql.NullInt64)
		default:
			return nil, fmt.Errorf("unexpected column %q for type BalanceLog", columns[i])
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the BalanceLog fields.
func (bl *BalanceLog) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case balancelog.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			bl.ID = int(value.Int64)
		case balancelog.FieldPrice:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field price", values[i])
			} else if value.Valid {
				bl.Price = int(value.Int64)
			}
		case balancelog.FieldType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field type", values[i])
			} else if value.Valid {
				bl.Type = balancelog.Type(value.String)
			}
		case balancelog.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field user_donor", value)
			} else if value.Valid {
				bl.user_donor = new(int)
				*bl.user_donor = int(value.Int64)
			}
		case balancelog.ForeignKeys[1]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field user_receiver", value)
			} else if value.Valid {
				bl.user_receiver = new(int)
				*bl.user_receiver = int(value.Int64)
			}
		}
	}
	return nil
}

// QueryDonor queries the "donor" edge of the BalanceLog entity.
func (bl *BalanceLog) QueryDonor() *UserQuery {
	return NewBalanceLogClient(bl.config).QueryDonor(bl)
}

// QueryReceiver queries the "receiver" edge of the BalanceLog entity.
func (bl *BalanceLog) QueryReceiver() *UserQuery {
	return NewBalanceLogClient(bl.config).QueryReceiver(bl)
}

// Update returns a builder for updating this BalanceLog.
// Note that you need to call BalanceLog.Unwrap() before calling this method if this BalanceLog
// was returned from a transaction, and the transaction was committed or rolled back.
func (bl *BalanceLog) Update() *BalanceLogUpdateOne {
	return NewBalanceLogClient(bl.config).UpdateOne(bl)
}

// Unwrap unwraps the BalanceLog entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (bl *BalanceLog) Unwrap() *BalanceLog {
	_tx, ok := bl.config.driver.(*txDriver)
	if !ok {
		panic("ent: BalanceLog is not a transactional entity")
	}
	bl.config.driver = _tx.drv
	return bl
}

// String implements the fmt.Stringer.
func (bl *BalanceLog) String() string {
	var builder strings.Builder
	builder.WriteString("BalanceLog(")
	builder.WriteString(fmt.Sprintf("id=%v, ", bl.ID))
	builder.WriteString("price=")
	builder.WriteString(fmt.Sprintf("%v", bl.Price))
	builder.WriteString(", ")
	builder.WriteString("type=")
	builder.WriteString(fmt.Sprintf("%v", bl.Type))
	builder.WriteByte(')')
	return builder.String()
}

// BalanceLogs is a parsable slice of BalanceLog.
type BalanceLogs []*BalanceLog
