// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/nishinoyama/kobuy-2/ent/grocery"
	"github.com/nishinoyama/kobuy-2/ent/predicate"
	"github.com/nishinoyama/kobuy-2/ent/user"
)

// GroceryUpdate is the builder for updating Grocery entities.
type GroceryUpdate struct {
	config
	hooks    []Hook
	mutation *GroceryMutation
}

// Where appends a list predicates to the GroceryUpdate builder.
func (gu *GroceryUpdate) Where(ps ...predicate.Grocery) *GroceryUpdate {
	gu.mutation.Where(ps...)
	return gu
}

// SetName sets the "name" field.
func (gu *GroceryUpdate) SetName(s string) *GroceryUpdate {
	gu.mutation.SetName(s)
	return gu
}

// SetProviderID sets the "provider" edge to the User entity by ID.
func (gu *GroceryUpdate) SetProviderID(id int) *GroceryUpdate {
	gu.mutation.SetProviderID(id)
	return gu
}

// SetNillableProviderID sets the "provider" edge to the User entity by ID if the given value is not nil.
func (gu *GroceryUpdate) SetNillableProviderID(id *int) *GroceryUpdate {
	if id != nil {
		gu = gu.SetProviderID(*id)
	}
	return gu
}

// SetProvider sets the "provider" edge to the User entity.
func (gu *GroceryUpdate) SetProvider(u *User) *GroceryUpdate {
	return gu.SetProviderID(u.ID)
}

// Mutation returns the GroceryMutation object of the builder.
func (gu *GroceryUpdate) Mutation() *GroceryMutation {
	return gu.mutation
}

// ClearProvider clears the "provider" edge to the User entity.
func (gu *GroceryUpdate) ClearProvider() *GroceryUpdate {
	gu.mutation.ClearProvider()
	return gu
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (gu *GroceryUpdate) Save(ctx context.Context) (int, error) {
	return withHooks[int, GroceryMutation](ctx, gu.sqlSave, gu.mutation, gu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (gu *GroceryUpdate) SaveX(ctx context.Context) int {
	affected, err := gu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (gu *GroceryUpdate) Exec(ctx context.Context) error {
	_, err := gu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (gu *GroceryUpdate) ExecX(ctx context.Context) {
	if err := gu.Exec(ctx); err != nil {
		panic(err)
	}
}

func (gu *GroceryUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(grocery.Table, grocery.Columns, sqlgraph.NewFieldSpec(grocery.FieldID, field.TypeInt))
	if ps := gu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := gu.mutation.Name(); ok {
		_spec.SetField(grocery.FieldName, field.TypeString, value)
	}
	if gu.mutation.ProviderCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   grocery.ProviderTable,
			Columns: []string{grocery.ProviderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := gu.mutation.ProviderIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   grocery.ProviderTable,
			Columns: []string{grocery.ProviderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, gu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{grocery.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	gu.mutation.done = true
	return n, nil
}

// GroceryUpdateOne is the builder for updating a single Grocery entity.
type GroceryUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *GroceryMutation
}

// SetName sets the "name" field.
func (guo *GroceryUpdateOne) SetName(s string) *GroceryUpdateOne {
	guo.mutation.SetName(s)
	return guo
}

// SetProviderID sets the "provider" edge to the User entity by ID.
func (guo *GroceryUpdateOne) SetProviderID(id int) *GroceryUpdateOne {
	guo.mutation.SetProviderID(id)
	return guo
}

// SetNillableProviderID sets the "provider" edge to the User entity by ID if the given value is not nil.
func (guo *GroceryUpdateOne) SetNillableProviderID(id *int) *GroceryUpdateOne {
	if id != nil {
		guo = guo.SetProviderID(*id)
	}
	return guo
}

// SetProvider sets the "provider" edge to the User entity.
func (guo *GroceryUpdateOne) SetProvider(u *User) *GroceryUpdateOne {
	return guo.SetProviderID(u.ID)
}

// Mutation returns the GroceryMutation object of the builder.
func (guo *GroceryUpdateOne) Mutation() *GroceryMutation {
	return guo.mutation
}

// ClearProvider clears the "provider" edge to the User entity.
func (guo *GroceryUpdateOne) ClearProvider() *GroceryUpdateOne {
	guo.mutation.ClearProvider()
	return guo
}

// Where appends a list predicates to the GroceryUpdate builder.
func (guo *GroceryUpdateOne) Where(ps ...predicate.Grocery) *GroceryUpdateOne {
	guo.mutation.Where(ps...)
	return guo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (guo *GroceryUpdateOne) Select(field string, fields ...string) *GroceryUpdateOne {
	guo.fields = append([]string{field}, fields...)
	return guo
}

// Save executes the query and returns the updated Grocery entity.
func (guo *GroceryUpdateOne) Save(ctx context.Context) (*Grocery, error) {
	return withHooks[*Grocery, GroceryMutation](ctx, guo.sqlSave, guo.mutation, guo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (guo *GroceryUpdateOne) SaveX(ctx context.Context) *Grocery {
	node, err := guo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (guo *GroceryUpdateOne) Exec(ctx context.Context) error {
	_, err := guo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (guo *GroceryUpdateOne) ExecX(ctx context.Context) {
	if err := guo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (guo *GroceryUpdateOne) sqlSave(ctx context.Context) (_node *Grocery, err error) {
	_spec := sqlgraph.NewUpdateSpec(grocery.Table, grocery.Columns, sqlgraph.NewFieldSpec(grocery.FieldID, field.TypeInt))
	id, ok := guo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Grocery.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := guo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, grocery.FieldID)
		for _, f := range fields {
			if !grocery.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != grocery.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := guo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := guo.mutation.Name(); ok {
		_spec.SetField(grocery.FieldName, field.TypeString, value)
	}
	if guo.mutation.ProviderCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   grocery.ProviderTable,
			Columns: []string{grocery.ProviderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := guo.mutation.ProviderIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   grocery.ProviderTable,
			Columns: []string{grocery.ProviderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Grocery{config: guo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, guo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{grocery.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	guo.mutation.done = true
	return _node, nil
}
