// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/nishinoyama/kobuy-2/ent/ledger"
	"github.com/nishinoyama/kobuy-2/ent/user"
)

// LedgerCreate is the builder for creating a Ledger entity.
type LedgerCreate struct {
	config
	mutation *LedgerMutation
	hooks    []Hook
}

// SetPrice sets the "price" field.
func (lc *LedgerCreate) SetPrice(i int) *LedgerCreate {
	lc.mutation.SetPrice(i)
	return lc
}

// SetType sets the "type" field.
func (lc *LedgerCreate) SetType(l ledger.Type) *LedgerCreate {
	lc.mutation.SetType(l)
	return lc
}

// SetDonorID sets the "donor" edge to the User entity by ID.
func (lc *LedgerCreate) SetDonorID(id int) *LedgerCreate {
	lc.mutation.SetDonorID(id)
	return lc
}

// SetNillableDonorID sets the "donor" edge to the User entity by ID if the given value is not nil.
func (lc *LedgerCreate) SetNillableDonorID(id *int) *LedgerCreate {
	if id != nil {
		lc = lc.SetDonorID(*id)
	}
	return lc
}

// SetDonor sets the "donor" edge to the User entity.
func (lc *LedgerCreate) SetDonor(u *User) *LedgerCreate {
	return lc.SetDonorID(u.ID)
}

// SetReceiverID sets the "receiver" edge to the User entity by ID.
func (lc *LedgerCreate) SetReceiverID(id int) *LedgerCreate {
	lc.mutation.SetReceiverID(id)
	return lc
}

// SetNillableReceiverID sets the "receiver" edge to the User entity by ID if the given value is not nil.
func (lc *LedgerCreate) SetNillableReceiverID(id *int) *LedgerCreate {
	if id != nil {
		lc = lc.SetReceiverID(*id)
	}
	return lc
}

// SetReceiver sets the "receiver" edge to the User entity.
func (lc *LedgerCreate) SetReceiver(u *User) *LedgerCreate {
	return lc.SetReceiverID(u.ID)
}

// Mutation returns the LedgerMutation object of the builder.
func (lc *LedgerCreate) Mutation() *LedgerMutation {
	return lc.mutation
}

// Save creates the Ledger in the database.
func (lc *LedgerCreate) Save(ctx context.Context) (*Ledger, error) {
	return withHooks[*Ledger, LedgerMutation](ctx, lc.sqlSave, lc.mutation, lc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (lc *LedgerCreate) SaveX(ctx context.Context) *Ledger {
	v, err := lc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (lc *LedgerCreate) Exec(ctx context.Context) error {
	_, err := lc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (lc *LedgerCreate) ExecX(ctx context.Context) {
	if err := lc.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (lc *LedgerCreate) check() error {
	if _, ok := lc.mutation.Price(); !ok {
		return &ValidationError{Name: "price", err: errors.New(`ent: missing required field "Ledger.price"`)}
	}
	if _, ok := lc.mutation.GetType(); !ok {
		return &ValidationError{Name: "type", err: errors.New(`ent: missing required field "Ledger.type"`)}
	}
	if v, ok := lc.mutation.GetType(); ok {
		if err := ledger.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "Ledger.type": %w`, err)}
		}
	}
	return nil
}

func (lc *LedgerCreate) sqlSave(ctx context.Context) (*Ledger, error) {
	if err := lc.check(); err != nil {
		return nil, err
	}
	_node, _spec := lc.createSpec()
	if err := sqlgraph.CreateNode(ctx, lc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	lc.mutation.id = &_node.ID
	lc.mutation.done = true
	return _node, nil
}

func (lc *LedgerCreate) createSpec() (*Ledger, *sqlgraph.CreateSpec) {
	var (
		_node = &Ledger{config: lc.config}
		_spec = sqlgraph.NewCreateSpec(ledger.Table, sqlgraph.NewFieldSpec(ledger.FieldID, field.TypeInt))
	)
	if value, ok := lc.mutation.Price(); ok {
		_spec.SetField(ledger.FieldPrice, field.TypeInt, value)
		_node.Price = value
	}
	if value, ok := lc.mutation.GetType(); ok {
		_spec.SetField(ledger.FieldType, field.TypeEnum, value)
		_node.Type = value
	}
	if nodes := lc.mutation.DonorIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   ledger.DonorTable,
			Columns: []string{ledger.DonorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.user_donor = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := lc.mutation.ReceiverIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   ledger.ReceiverTable,
			Columns: []string{ledger.ReceiverColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.user_receiver = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// LedgerCreateBulk is the builder for creating many Ledger entities in bulk.
type LedgerCreateBulk struct {
	config
	builders []*LedgerCreate
}

// Save creates the Ledger entities in the database.
func (lcb *LedgerCreateBulk) Save(ctx context.Context) ([]*Ledger, error) {
	specs := make([]*sqlgraph.CreateSpec, len(lcb.builders))
	nodes := make([]*Ledger, len(lcb.builders))
	mutators := make([]Mutator, len(lcb.builders))
	for i := range lcb.builders {
		func(i int, root context.Context) {
			builder := lcb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*LedgerMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, lcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, lcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, lcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (lcb *LedgerCreateBulk) SaveX(ctx context.Context) []*Ledger {
	v, err := lcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (lcb *LedgerCreateBulk) Exec(ctx context.Context) error {
	_, err := lcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (lcb *LedgerCreateBulk) ExecX(ctx context.Context) {
	if err := lcb.Exec(ctx); err != nil {
		panic(err)
	}
}
