// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/nishinoyama/kobuy-2/pkg/ent/grocery"
	"github.com/nishinoyama/kobuy-2/pkg/ent/predicate"
	"github.com/nishinoyama/kobuy-2/pkg/ent/purchase"
	"github.com/nishinoyama/kobuy-2/pkg/ent/user"
)

// GroceryQuery is the builder for querying Grocery entities.
type GroceryQuery struct {
	config
	ctx           *QueryContext
	order         []OrderFunc
	inters        []Interceptor
	predicates    []predicate.Grocery
	withProvider  *UserQuery
	withPurchased *PurchaseQuery
	withFKs       bool
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the GroceryQuery builder.
func (gq *GroceryQuery) Where(ps ...predicate.Grocery) *GroceryQuery {
	gq.predicates = append(gq.predicates, ps...)
	return gq
}

// Limit the number of records to be returned by this query.
func (gq *GroceryQuery) Limit(limit int) *GroceryQuery {
	gq.ctx.Limit = &limit
	return gq
}

// Offset to start from.
func (gq *GroceryQuery) Offset(offset int) *GroceryQuery {
	gq.ctx.Offset = &offset
	return gq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (gq *GroceryQuery) Unique(unique bool) *GroceryQuery {
	gq.ctx.Unique = &unique
	return gq
}

// Order specifies how the records should be ordered.
func (gq *GroceryQuery) Order(o ...OrderFunc) *GroceryQuery {
	gq.order = append(gq.order, o...)
	return gq
}

// QueryProvider chains the current query on the "provider" edge.
func (gq *GroceryQuery) QueryProvider() *UserQuery {
	query := (&UserClient{config: gq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := gq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := gq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(grocery.Table, grocery.FieldID, selector),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, grocery.ProviderTable, grocery.ProviderColumn),
		)
		fromU = sqlgraph.SetNeighbors(gq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryPurchased chains the current query on the "purchased" edge.
func (gq *GroceryQuery) QueryPurchased() *PurchaseQuery {
	query := (&PurchaseClient{config: gq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := gq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := gq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(grocery.Table, grocery.FieldID, selector),
			sqlgraph.To(purchase.Table, purchase.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, grocery.PurchasedTable, grocery.PurchasedColumn),
		)
		fromU = sqlgraph.SetNeighbors(gq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first Grocery entity from the query.
// Returns a *NotFoundError when no Grocery was found.
func (gq *GroceryQuery) First(ctx context.Context) (*Grocery, error) {
	nodes, err := gq.Limit(1).All(setContextOp(ctx, gq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{grocery.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (gq *GroceryQuery) FirstX(ctx context.Context) *Grocery {
	node, err := gq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first Grocery ID from the query.
// Returns a *NotFoundError when no Grocery ID was found.
func (gq *GroceryQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = gq.Limit(1).IDs(setContextOp(ctx, gq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{grocery.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (gq *GroceryQuery) FirstIDX(ctx context.Context) int {
	id, err := gq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single Grocery entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one Grocery entity is found.
// Returns a *NotFoundError when no Grocery entities are found.
func (gq *GroceryQuery) Only(ctx context.Context) (*Grocery, error) {
	nodes, err := gq.Limit(2).All(setContextOp(ctx, gq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{grocery.Label}
	default:
		return nil, &NotSingularError{grocery.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (gq *GroceryQuery) OnlyX(ctx context.Context) *Grocery {
	node, err := gq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only Grocery ID in the query.
// Returns a *NotSingularError when more than one Grocery ID is found.
// Returns a *NotFoundError when no entities are found.
func (gq *GroceryQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = gq.Limit(2).IDs(setContextOp(ctx, gq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{grocery.Label}
	default:
		err = &NotSingularError{grocery.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (gq *GroceryQuery) OnlyIDX(ctx context.Context) int {
	id, err := gq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of Groceries.
func (gq *GroceryQuery) All(ctx context.Context) ([]*Grocery, error) {
	ctx = setContextOp(ctx, gq.ctx, "All")
	if err := gq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*Grocery, *GroceryQuery]()
	return withInterceptors[[]*Grocery](ctx, gq, qr, gq.inters)
}

// AllX is like All, but panics if an error occurs.
func (gq *GroceryQuery) AllX(ctx context.Context) []*Grocery {
	nodes, err := gq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of Grocery IDs.
func (gq *GroceryQuery) IDs(ctx context.Context) (ids []int, err error) {
	if gq.ctx.Unique == nil && gq.path != nil {
		gq.Unique(true)
	}
	ctx = setContextOp(ctx, gq.ctx, "IDs")
	if err = gq.Select(grocery.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (gq *GroceryQuery) IDsX(ctx context.Context) []int {
	ids, err := gq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (gq *GroceryQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, gq.ctx, "Count")
	if err := gq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, gq, querierCount[*GroceryQuery](), gq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (gq *GroceryQuery) CountX(ctx context.Context) int {
	count, err := gq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (gq *GroceryQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, gq.ctx, "Exist")
	switch _, err := gq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (gq *GroceryQuery) ExistX(ctx context.Context) bool {
	exist, err := gq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the GroceryQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (gq *GroceryQuery) Clone() *GroceryQuery {
	if gq == nil {
		return nil
	}
	return &GroceryQuery{
		config:        gq.config,
		ctx:           gq.ctx.Clone(),
		order:         append([]OrderFunc{}, gq.order...),
		inters:        append([]Interceptor{}, gq.inters...),
		predicates:    append([]predicate.Grocery{}, gq.predicates...),
		withProvider:  gq.withProvider.Clone(),
		withPurchased: gq.withPurchased.Clone(),
		// clone intermediate query.
		sql:  gq.sql.Clone(),
		path: gq.path,
	}
}

// WithProvider tells the query-builder to eager-load the nodes that are connected to
// the "provider" edge. The optional arguments are used to configure the query builder of the edge.
func (gq *GroceryQuery) WithProvider(opts ...func(*UserQuery)) *GroceryQuery {
	query := (&UserClient{config: gq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	gq.withProvider = query
	return gq
}

// WithPurchased tells the query-builder to eager-load the nodes that are connected to
// the "purchased" edge. The optional arguments are used to configure the query builder of the edge.
func (gq *GroceryQuery) WithPurchased(opts ...func(*PurchaseQuery)) *GroceryQuery {
	query := (&PurchaseClient{config: gq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	gq.withPurchased = query
	return gq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Name string `json:"name,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.Grocery.Query().
//		GroupBy(grocery.FieldName).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (gq *GroceryQuery) GroupBy(field string, fields ...string) *GroceryGroupBy {
	gq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &GroceryGroupBy{build: gq}
	grbuild.flds = &gq.ctx.Fields
	grbuild.label = grocery.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Name string `json:"name,omitempty"`
//	}
//
//	client.Grocery.Query().
//		Select(grocery.FieldName).
//		Scan(ctx, &v)
func (gq *GroceryQuery) Select(fields ...string) *GrocerySelect {
	gq.ctx.Fields = append(gq.ctx.Fields, fields...)
	sbuild := &GrocerySelect{GroceryQuery: gq}
	sbuild.label = grocery.Label
	sbuild.flds, sbuild.scan = &gq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a GrocerySelect configured with the given aggregations.
func (gq *GroceryQuery) Aggregate(fns ...AggregateFunc) *GrocerySelect {
	return gq.Select().Aggregate(fns...)
}

func (gq *GroceryQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range gq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, gq); err != nil {
				return err
			}
		}
	}
	for _, f := range gq.ctx.Fields {
		if !grocery.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if gq.path != nil {
		prev, err := gq.path(ctx)
		if err != nil {
			return err
		}
		gq.sql = prev
	}
	return nil
}

func (gq *GroceryQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*Grocery, error) {
	var (
		nodes       = []*Grocery{}
		withFKs     = gq.withFKs
		_spec       = gq.querySpec()
		loadedTypes = [2]bool{
			gq.withProvider != nil,
			gq.withPurchased != nil,
		}
	)
	if gq.withProvider != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, grocery.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*Grocery).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &Grocery{config: gq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, gq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := gq.withProvider; query != nil {
		if err := gq.loadProvider(ctx, query, nodes, nil,
			func(n *Grocery, e *User) { n.Edges.Provider = e }); err != nil {
			return nil, err
		}
	}
	if query := gq.withPurchased; query != nil {
		if err := gq.loadPurchased(ctx, query, nodes,
			func(n *Grocery) { n.Edges.Purchased = []*Purchase{} },
			func(n *Grocery, e *Purchase) { n.Edges.Purchased = append(n.Edges.Purchased, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (gq *GroceryQuery) loadProvider(ctx context.Context, query *UserQuery, nodes []*Grocery, init func(*Grocery), assign func(*Grocery, *User)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*Grocery)
	for i := range nodes {
		if nodes[i].user_provided_groceries == nil {
			continue
		}
		fk := *nodes[i].user_provided_groceries
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(user.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "user_provided_groceries" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (gq *GroceryQuery) loadPurchased(ctx context.Context, query *PurchaseQuery, nodes []*Grocery, init func(*Grocery), assign func(*Grocery, *Purchase)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*Grocery)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	query.withFKs = true
	query.Where(predicate.Purchase(func(s *sql.Selector) {
		s.Where(sql.InValues(grocery.PurchasedColumn, fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.grocery_purchased
		if fk == nil {
			return fmt.Errorf(`foreign-key "grocery_purchased" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "grocery_purchased" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (gq *GroceryQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := gq.querySpec()
	_spec.Node.Columns = gq.ctx.Fields
	if len(gq.ctx.Fields) > 0 {
		_spec.Unique = gq.ctx.Unique != nil && *gq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, gq.driver, _spec)
}

func (gq *GroceryQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(grocery.Table, grocery.Columns, sqlgraph.NewFieldSpec(grocery.FieldID, field.TypeInt))
	_spec.From = gq.sql
	if unique := gq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if gq.path != nil {
		_spec.Unique = true
	}
	if fields := gq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, grocery.FieldID)
		for i := range fields {
			if fields[i] != grocery.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := gq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := gq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := gq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := gq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (gq *GroceryQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(gq.driver.Dialect())
	t1 := builder.Table(grocery.Table)
	columns := gq.ctx.Fields
	if len(columns) == 0 {
		columns = grocery.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if gq.sql != nil {
		selector = gq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if gq.ctx.Unique != nil && *gq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range gq.predicates {
		p(selector)
	}
	for _, p := range gq.order {
		p(selector)
	}
	if offset := gq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := gq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// GroceryGroupBy is the group-by builder for Grocery entities.
type GroceryGroupBy struct {
	selector
	build *GroceryQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (ggb *GroceryGroupBy) Aggregate(fns ...AggregateFunc) *GroceryGroupBy {
	ggb.fns = append(ggb.fns, fns...)
	return ggb
}

// Scan applies the selector query and scans the result into the given value.
func (ggb *GroceryGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, ggb.build.ctx, "GroupBy")
	if err := ggb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*GroceryQuery, *GroceryGroupBy](ctx, ggb.build, ggb, ggb.build.inters, v)
}

func (ggb *GroceryGroupBy) sqlScan(ctx context.Context, root *GroceryQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(ggb.fns))
	for _, fn := range ggb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*ggb.flds)+len(ggb.fns))
		for _, f := range *ggb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*ggb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := ggb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// GrocerySelect is the builder for selecting fields of Grocery entities.
type GrocerySelect struct {
	*GroceryQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (gs *GrocerySelect) Aggregate(fns ...AggregateFunc) *GrocerySelect {
	gs.fns = append(gs.fns, fns...)
	return gs
}

// Scan applies the selector query and scans the result into the given value.
func (gs *GrocerySelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, gs.ctx, "Select")
	if err := gs.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*GroceryQuery, *GrocerySelect](ctx, gs.GroceryQuery, gs, gs.inters, v)
}

func (gs *GrocerySelect) sqlScan(ctx context.Context, root *GroceryQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(gs.fns))
	for _, fn := range gs.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*gs.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := gs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
