// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/nishinoyama/kobuy-2/pkg/ent/ledger"
	"github.com/nishinoyama/kobuy-2/pkg/ent/predicate"
	"github.com/nishinoyama/kobuy-2/pkg/ent/user"
)

// LedgerUpdate is the builder for updating Ledger entities.
type LedgerUpdate struct {
	config
	hooks    []Hook
	mutation *LedgerMutation
}

// Where appends a list predicates to the LedgerUpdate builder.
func (lu *LedgerUpdate) Where(ps ...predicate.Ledger) *LedgerUpdate {
	lu.mutation.Where(ps...)
	return lu
}

// SetPrice sets the "price" field.
func (lu *LedgerUpdate) SetPrice(i int) *LedgerUpdate {
	lu.mutation.ResetPrice()
	lu.mutation.SetPrice(i)
	return lu
}

// AddPrice adds i to the "price" field.
func (lu *LedgerUpdate) AddPrice(i int) *LedgerUpdate {
	lu.mutation.AddPrice(i)
	return lu
}

// SetType sets the "type" field.
func (lu *LedgerUpdate) SetType(l ledger.Type) *LedgerUpdate {
	lu.mutation.SetType(l)
	return lu
}

// SetPayerID sets the "payer" edge to the User entity by ID.
func (lu *LedgerUpdate) SetPayerID(id int) *LedgerUpdate {
	lu.mutation.SetPayerID(id)
	return lu
}

// SetNillablePayerID sets the "payer" edge to the User entity by ID if the given value is not nil.
func (lu *LedgerUpdate) SetNillablePayerID(id *int) *LedgerUpdate {
	if id != nil {
		lu = lu.SetPayerID(*id)
	}
	return lu
}

// SetPayer sets the "payer" edge to the User entity.
func (lu *LedgerUpdate) SetPayer(u *User) *LedgerUpdate {
	return lu.SetPayerID(u.ID)
}

// SetReceiverID sets the "receiver" edge to the User entity by ID.
func (lu *LedgerUpdate) SetReceiverID(id int) *LedgerUpdate {
	lu.mutation.SetReceiverID(id)
	return lu
}

// SetNillableReceiverID sets the "receiver" edge to the User entity by ID if the given value is not nil.
func (lu *LedgerUpdate) SetNillableReceiverID(id *int) *LedgerUpdate {
	if id != nil {
		lu = lu.SetReceiverID(*id)
	}
	return lu
}

// SetReceiver sets the "receiver" edge to the User entity.
func (lu *LedgerUpdate) SetReceiver(u *User) *LedgerUpdate {
	return lu.SetReceiverID(u.ID)
}

// Mutation returns the LedgerMutation object of the builder.
func (lu *LedgerUpdate) Mutation() *LedgerMutation {
	return lu.mutation
}

// ClearPayer clears the "payer" edge to the User entity.
func (lu *LedgerUpdate) ClearPayer() *LedgerUpdate {
	lu.mutation.ClearPayer()
	return lu
}

// ClearReceiver clears the "receiver" edge to the User entity.
func (lu *LedgerUpdate) ClearReceiver() *LedgerUpdate {
	lu.mutation.ClearReceiver()
	return lu
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (lu *LedgerUpdate) Save(ctx context.Context) (int, error) {
	return withHooks[int, LedgerMutation](ctx, lu.sqlSave, lu.mutation, lu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (lu *LedgerUpdate) SaveX(ctx context.Context) int {
	affected, err := lu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (lu *LedgerUpdate) Exec(ctx context.Context) error {
	_, err := lu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (lu *LedgerUpdate) ExecX(ctx context.Context) {
	if err := lu.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (lu *LedgerUpdate) check() error {
	if v, ok := lu.mutation.GetType(); ok {
		if err := ledger.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "Ledger.type": %w`, err)}
		}
	}
	return nil
}

func (lu *LedgerUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := lu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(ledger.Table, ledger.Columns, sqlgraph.NewFieldSpec(ledger.FieldID, field.TypeInt))
	if ps := lu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := lu.mutation.Price(); ok {
		_spec.SetField(ledger.FieldPrice, field.TypeInt, value)
	}
	if value, ok := lu.mutation.AddedPrice(); ok {
		_spec.AddField(ledger.FieldPrice, field.TypeInt, value)
	}
	if value, ok := lu.mutation.GetType(); ok {
		_spec.SetField(ledger.FieldType, field.TypeEnum, value)
	}
	if lu.mutation.PayerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   ledger.PayerTable,
			Columns: []string{ledger.PayerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := lu.mutation.PayerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   ledger.PayerTable,
			Columns: []string{ledger.PayerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if lu.mutation.ReceiverCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   ledger.ReceiverTable,
			Columns: []string{ledger.ReceiverColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := lu.mutation.ReceiverIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   ledger.ReceiverTable,
			Columns: []string{ledger.ReceiverColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, lu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{ledger.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	lu.mutation.done = true
	return n, nil
}

// LedgerUpdateOne is the builder for updating a single Ledger entity.
type LedgerUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *LedgerMutation
}

// SetPrice sets the "price" field.
func (luo *LedgerUpdateOne) SetPrice(i int) *LedgerUpdateOne {
	luo.mutation.ResetPrice()
	luo.mutation.SetPrice(i)
	return luo
}

// AddPrice adds i to the "price" field.
func (luo *LedgerUpdateOne) AddPrice(i int) *LedgerUpdateOne {
	luo.mutation.AddPrice(i)
	return luo
}

// SetType sets the "type" field.
func (luo *LedgerUpdateOne) SetType(l ledger.Type) *LedgerUpdateOne {
	luo.mutation.SetType(l)
	return luo
}

// SetPayerID sets the "payer" edge to the User entity by ID.
func (luo *LedgerUpdateOne) SetPayerID(id int) *LedgerUpdateOne {
	luo.mutation.SetPayerID(id)
	return luo
}

// SetNillablePayerID sets the "payer" edge to the User entity by ID if the given value is not nil.
func (luo *LedgerUpdateOne) SetNillablePayerID(id *int) *LedgerUpdateOne {
	if id != nil {
		luo = luo.SetPayerID(*id)
	}
	return luo
}

// SetPayer sets the "payer" edge to the User entity.
func (luo *LedgerUpdateOne) SetPayer(u *User) *LedgerUpdateOne {
	return luo.SetPayerID(u.ID)
}

// SetReceiverID sets the "receiver" edge to the User entity by ID.
func (luo *LedgerUpdateOne) SetReceiverID(id int) *LedgerUpdateOne {
	luo.mutation.SetReceiverID(id)
	return luo
}

// SetNillableReceiverID sets the "receiver" edge to the User entity by ID if the given value is not nil.
func (luo *LedgerUpdateOne) SetNillableReceiverID(id *int) *LedgerUpdateOne {
	if id != nil {
		luo = luo.SetReceiverID(*id)
	}
	return luo
}

// SetReceiver sets the "receiver" edge to the User entity.
func (luo *LedgerUpdateOne) SetReceiver(u *User) *LedgerUpdateOne {
	return luo.SetReceiverID(u.ID)
}

// Mutation returns the LedgerMutation object of the builder.
func (luo *LedgerUpdateOne) Mutation() *LedgerMutation {
	return luo.mutation
}

// ClearPayer clears the "payer" edge to the User entity.
func (luo *LedgerUpdateOne) ClearPayer() *LedgerUpdateOne {
	luo.mutation.ClearPayer()
	return luo
}

// ClearReceiver clears the "receiver" edge to the User entity.
func (luo *LedgerUpdateOne) ClearReceiver() *LedgerUpdateOne {
	luo.mutation.ClearReceiver()
	return luo
}

// Where appends a list predicates to the LedgerUpdate builder.
func (luo *LedgerUpdateOne) Where(ps ...predicate.Ledger) *LedgerUpdateOne {
	luo.mutation.Where(ps...)
	return luo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (luo *LedgerUpdateOne) Select(field string, fields ...string) *LedgerUpdateOne {
	luo.fields = append([]string{field}, fields...)
	return luo
}

// Save executes the query and returns the updated Ledger entity.
func (luo *LedgerUpdateOne) Save(ctx context.Context) (*Ledger, error) {
	return withHooks[*Ledger, LedgerMutation](ctx, luo.sqlSave, luo.mutation, luo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (luo *LedgerUpdateOne) SaveX(ctx context.Context) *Ledger {
	node, err := luo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (luo *LedgerUpdateOne) Exec(ctx context.Context) error {
	_, err := luo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (luo *LedgerUpdateOne) ExecX(ctx context.Context) {
	if err := luo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (luo *LedgerUpdateOne) check() error {
	if v, ok := luo.mutation.GetType(); ok {
		if err := ledger.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "Ledger.type": %w`, err)}
		}
	}
	return nil
}

func (luo *LedgerUpdateOne) sqlSave(ctx context.Context) (_node *Ledger, err error) {
	if err := luo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(ledger.Table, ledger.Columns, sqlgraph.NewFieldSpec(ledger.FieldID, field.TypeInt))
	id, ok := luo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Ledger.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := luo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, ledger.FieldID)
		for _, f := range fields {
			if !ledger.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != ledger.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := luo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := luo.mutation.Price(); ok {
		_spec.SetField(ledger.FieldPrice, field.TypeInt, value)
	}
	if value, ok := luo.mutation.AddedPrice(); ok {
		_spec.AddField(ledger.FieldPrice, field.TypeInt, value)
	}
	if value, ok := luo.mutation.GetType(); ok {
		_spec.SetField(ledger.FieldType, field.TypeEnum, value)
	}
	if luo.mutation.PayerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   ledger.PayerTable,
			Columns: []string{ledger.PayerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := luo.mutation.PayerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   ledger.PayerTable,
			Columns: []string{ledger.PayerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if luo.mutation.ReceiverCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   ledger.ReceiverTable,
			Columns: []string{ledger.ReceiverColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := luo.mutation.ReceiverIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   ledger.ReceiverTable,
			Columns: []string{ledger.ReceiverColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Ledger{config: luo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, luo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{ledger.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	luo.mutation.done = true
	return _node, nil
}
