// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// BalanceLog is the predicate function for balancelog builders.
type BalanceLog func(*sql.Selector)

// Grocery is the predicate function for grocery builders.
type Grocery func(*sql.Selector)

// Purchase is the predicate function for purchase builders.
type Purchase func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
