// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Grocery is the predicate function for grocery builders.
type Grocery func(*sql.Selector)

// Ledger is the predicate function for ledger builders.
type Ledger func(*sql.Selector)

// Purchase is the predicate function for purchase builders.
type Purchase func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
